import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Geist } from 'next/font/google';
import { cn } from '@/lib/utils';
import Footer from '@/components/layout/Footer';
import Header from '@/components/layout/Header';
import Container from '@/components/layout/Container';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const pretendard = localFont({
  src: [
    {
      path: '../public/fonts/Pretendard-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Pretendard-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      suppressHydrationWarning
      className={cn(pretendard.variable, 'font-sans', geist.variable)}
    >
      <body className={`${pretendard.className} txt-b-regular flex min-h-screen flex-col`}>
        <Header />
        <main className="bg-special-dark-blue-900 h-auto flex-1 lg:px-[100px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
